name: MonthlyUpdate
on:
  workflow_dispatch:
    inputs:
      filename:
        description: "Artifact name"
        required: true
      stars:
        description: "List of stars of the month"
        required: true
      weeks:
        description: "List of weekly updates"
        required: true
      roads:
        description: "List of roads ahead"
        required: true

jobs:
  render:
    name: Render
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: yarn
      - run: echo $WORKFLOW_INPUT > input-props.json
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: yarn build ${{ github.workflow }} --props="./input-props.json" 150 300 550 850 1100 1400 1800 2000 2350 2600 2900 3300 3500 3800 4200 4400 4550 4800 5000 5250 5500 5700 5900 6150 6350 6600 6800 7000 7270 7550 8100
      - uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ github.event.inputs.filename }}
          path: out/
